<div class="container my-5">
    <button class="btn btn-secondary" on:click={() => window.history.back()}>
        Back to Main Page
    </button>

    <hr>

    <h2>Week 1: 9/14/2026</h2>
    <h1>Civic vs Social Impact vs Public Interest Tech</h1>
    <p><i>By: Kateryna Morhun</i></p>

    <p>It’s not a groundbreaking declaration to say that a lot of technology and software is being produced and deployed today. With the obvious caveats about bloated bureaucracy, ineffective team management, etc, the tech industry has developed institutional knowledge about building MVPs, soliciting user feedback, A/B testing, and continuously improving the value add of their product. Hopefully, it is also not a groundbreaking observation that most of that software development expertise is not directed towards improving the lives of everyday people, and certainly not towards supporting historically marginalized or underrepresented communities. Traditional software builds a solution to a business problem that someone is willing to pay for. Success is usually evaluated in terms of quarterly revenue and shareholder value generated, and the designers are a bunch of engineers and product managers aiming to generate more value for those customers and shareholders. If we’re lucky, there are some guardrails in the form of policies, industry standards, or even individuals’ moral compasses, preventing this dynamic from spiraling into an active detriment to the people’s lives.</p>

    <p>But we’re often not lucky, and over the past few decades, institutions like <a href="https://morethancode.cc/report/introduction/">#MoreThanCode</a>, individuals like <a href="https://press.princeton.edu/books/hardcover/9780691207759/power-to-the-public">Tara Dawson McGuinness and Hana Schank</a>, and many others, have made an effort to imagine and cultivate communities within the broader development ecosystem that address the lack of governance and emphasis on public benefit and social justice in traditional software engineering. Terms like <i>Civic Tech</i>, <i>Social Impact Tech</i>, and <i>Public Interest Tech</i> have gotten lots of screentime in the past few decades, but they’re often used interchangeably, even though they can express different values and visions of tech used for social good.</p>
    
    <p>These definitions are my opinions, and I, too, have used the terms interchangeably as I’ve grappled with defining and declaring my own pursuits and priorities to friends, employers, and fellow community members. Admittedly, I waffle on whether or not I should care about exactly delineating the differences between the terms, because I feel that, at the end of the day, many projects and initiatives started by thoughtful practitioners that aim to improve people’s lives could fall into any or all of these categories. The rest is marketing, to encourage adoption, to strive to make a broader impact, and to build a community of like-minded practitioners.</p>
    
    <p>On that note, McGuinness and Schank note that the definitions of Civic Tech and Public Interest Tech have evolved and shifted since the origins of Civic Tech post World War II and the 2009 Open Government Directive of the Obama Administration. To me, having entered the space more recently, Civic Tech limits its problem space to improving government processes and bureaucracy. Initiatives like <a href="https://formfest.org/">Form Fest</a> come to mind. While certainly an important pursuit, the framing of Civic Tech leaves out a focus on positive social impact. Government data can be made more transparent without actually tackling meaningful social changes. The positive social impact might happen accidentally as a side effect of a more digitized, modernized government process, but the framing emphasizes beneficiaries who are internal stakeholders within the government. This framing also emphasizes to me a vision of governments as being the only arbiters and executors of positive social impact. Given the public sector’s perennial challenge with funding and headcount, I believe the framing of all tech for social good being “civic” would absolve the private sector from any involvement or responsibility for contributing to the social good.</p>
    
    <div class="float-end ms-3" style="max-width: 40%;">
        <img src="stacky.png" alt="The UI of Stacky, an alternative mastodon-based social media platform that I worked on in 2024. There is a central column of posts in the center, and discoverable 'stacks' of related posts that appear along the right column as the user scrolls" class="img-fluid" style="width: 100%;" />
    </div>

    <p>When I think of Social Impact Tech, I think of largely private actors like public benefit corporations (e.g. <a href="https://www.desmos.com/">Desmos</a>), non-profit organizations like <a href="https://www.khanacademy.org/">Khanacademy</a>, and academic institutions that have attempted to merge market (or publishing) incentives with a desire to have a positive impact on society. The framing of tech for social good as Social Impact Tech carries with it more built-in responsibility for private actors to put their resources towards positive social impact, and their measure of success is often a balancing act between profit/publishing and impact. As a specific example, in 2024, I worked with a group at Johns Hopkins University on an alternative mastodon-based social media platform aiming for a less polarized and more pro-social social media experience. The team of builders included students and professors of sociology, human-computer interaction, and natural language processing, and we grappled with developing a pro-social recommendation algorithm and social media UI. This was a project that could only exist outside of government contexts due to the nature of social media, and outside of corporate contexts, due to the nature of market pressures to turn a profit.</p>
    
    <p>This framing is broader in scope than Civic Tech, but perhaps the reason it didn't win over Public Interest Tech as the primary term for “tech for social good” is because of the latter term’s association with past initiatives in other fields (though honestly, this differentiation is pedantic). Overall, Public Interest Tech and Social Impact Tech refer to largely the same types of technologies, and the terminology is inspired by the <a href="https://www.newamerica.org/insights/problem-solving-government/a-note-on-terminology/">“Public Interest Law” movement</a> of the 70s, when the Ford Foundation began funding private lawyers to redirect their lawyering acumen from serving the interests of corporations and wealthy clients to serving the interests of underrepresented communities. McGuinness and Schank define Public Interest Tech as "Design informed by real human needs, the use of real-time data to guide problem solving, and a focus on delivery in order to continuously learn and improve," which I agree with! It reads as a way to encapsulate the philosophy of redirecting the expertise and experience of technologists in designing and delivering products from serving the interests of corporations and wealthy shareholders to serving the interests of underrepresented communities.</p>
    
    <p>I don't think the Public Interest Tech community in the US has solved the problem of the ideal public-private partnership in building tech for social good -- we still haven't perfected the structures around who builds the tech, who bankrolls it, and who maintains it after its initial phase. Projects which were created as internal private tools, spun off into startups providing valuable services to local governments, struggled to monetize and grow enough to satisfy investors, only to be sold to another private company and removed from public accessibility, are too common an occurrence. But I find it necessary to have the conviction that one way or another, we will develop better, more sustainable ways of building and maintaining Public Interest Tech that not only survive the pressures of the market, but manage to redefine the incentives entirely.</p>
</div>